apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bind.fullname" . }}-named-conf
  labels:
    {{- include "bind.labels" . | nindent 4 }}
data:
  named.conf: |-
    options {
            directory "/var/cache/bind";
    
            // If there is a firewall between you and nameservers you want
            // to talk to, you may need to fix the firewall to allow multiple
            // ports to talk.  See http://www.kb.cert.org/vuls/id/800113
  
            // If your ISP provided one or more IP addresses for stable
            // nameservers, you probably want to use them as forwarders.
            // Uncomment the following block, and insert the addresses replacing
            // the all-0's placeholder.
  
             forwarders {
{{ .Values.domain.forwarder | indent 17 }};
             };

            //========================================================================
            // If BIND logs error messages about the root key being expired,
            // you will need to update your keys.  See https://www.isc.org/bind-keys
            //========================================================================
            dnssec-validation no;
            auth-nxdomain no;
            filter-aaaa-on-v4 yes;

            listen-on-v6 { any; };
            allow-recursion { any; };
            allow-query { any; };
            allow-query-cache { any; };
    };

    zone
{{- .Values.domain.name | quote | indent 1 }} {
        type master;
        file "/etc/bind/records.db";
        allow-transfer { any; };
    };
