apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bind.fullname" . }}-records-db
  labels:
    {{- include "bind.labels" . | nindent 4 }}
data:
  records.db: |-
    ;
    ;
    $TTL    604800
    @       IN      SOA
{{- .Values.domain.name | indent 5 }}. root.localhost. (
                                  2         ; Serial
                             604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                             604800 )       ; Negative Cache TTL
    ;
    @       IN      NS      localhost.
    @       IN      A       127.0.0.1
    @       IN      AAAA    ::1
{{ range $records := $.Values.records }}
{{- $records.name | indent 4 }} IN
{{- $records.type | indent 1}}
{{- $records.target | indent 1}}
{{ end }}