apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind.fullname" . }}
  labels:
    {{- include "bind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "bind.selectorLabels" . | nindent 4 }}
